# Example fly.io config which should work for now on the free tier.

# Note that by default after a launch fly will deploy 2 instances which doesn't
# work just yet due to websockets. Just run `fly scale count 1` after launch to
# fix that and then use `fly deploy --ha=false`.

app = "<NAME>"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
